// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-pages/ForgotPassword.tsx": () => import("../components/mockups/auth-pages/ForgotPassword.tsx"),
  "./components/mockups/auth-pages/Login.tsx": () => import("../components/mockups/auth-pages/Login.tsx"),
  "./components/mockups/auth-pages/Register.tsx": () => import("../components/mockups/auth-pages/Register.tsx"),
  "./components/mockups/auth-pages/ResetPassword.tsx": () => import("../components/mockups/auth-pages/ResetPassword.tsx")
};
